### ISSUE TITLE
Folia check is not working

### ISSUE THREAD

**Issue by SirSalad** [FancyMcPlugins/FancyLib#2]
It appears that Paper pulled some of Folia's patches and the current Folia check falsely flags a Paper server as Folia (Paper 1.20.1 b62). However, the Folia scheduler methods do work on a Paper based server

My current idea is to either check if `PluginMeta#isFoliaSupported` exists at runtime, or use the new Folia scheduler methods that were pulled to Paper.

Also, I believe there are `50_000_000` nanoseconds in a tick, not `2_500_000` implemented by #1 (1 tick = 50ms = 50,000,000 ns)

**Comment by OliverSchlueter** [comment]
You're right, but I think using the Folia schedulers should work with paper too.
Just in case, it now should be fixed (c5c3d0be93770fcd1b462ab754d0cca90b530807)

The nanoseconds problem is fixed too (2ca9b12b1b2028635a3c1146d2765bbdcd82a379)
